server:
  port: 9192
  
spring:
  h2:
    console:
      enabled: true  
  application:
    name: payment-service
  zipkin:
    base-url: http://localhost:9411/     
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka 
      
logging:
  file:
    name: C:\\logs\\microservice.log         

    